# This main config file overwrites the other subconfigs
experiment_name: test-models
overwrite: True
# stage: 
#   - generate
#   # Options for the stages: (multi-select)
#   # - generate
#   # - run
#   # - evaluate
#   # - aggregate
#   # - visualize
configs:
  - data: "data/main_data.yaml" # generates (or loads) data
  - run_model: "models/run_model.yaml" # get model configs (also on which dataset to run)
  - evaluation: "evaluation/default_evaluation.yaml" # evaluates models
  - aggregation: "aggregation/default_aggregation.yaml" # sweeps over runs
  - visualization: "visualization/default_visualization.yaml" # visualizes results

  