# This main config file overwrites the other subconfigs
experiment_name: my-default-run
overwrite: True
# stage: 
#   - generate
#   # Options for the stages: (multi-select)
#   # - generate
#   # - run
#   # - evaluate
#   # - aggregate
#   # - visualize
configs:
  - data: "data/main_data.yaml" # generates (or loads) data
  - model: "models/default_model.yaml" # get models
  - evaluation: "evaluation/default_evaluation.yaml" # evaluates models
  - aggreggation: "aggregation/default_aggregation.yaml" # sweeps over runs
  - visualization: "visualization/default_visualization.yaml" # visualizes results

  